# np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [3]:
np.sort(a)

array([ 7, 10, 17, 17, 26, 27, 38, 41, 49, 54, 56, 64, 89, 95, 96])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)

In [5]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

np.sort(b) # It gives sorting element row wise

In [9]:
np.sort(b,axis=0)       # axis=0 for column and axis=1 for raws

array([[41, 11,  8, 21],
       [70, 30, 40, 28],
       [71, 46, 62, 38],
       [79, 61, 68, 57],
       [81, 72, 91, 60],
       [82, 74, 99, 63]])

In [10]:
np.sort(a)[::-1]

array([96, 95, 89, 64, 56, 54, 49, 41, 38, 27, 26, 17, 17, 10,  7])

# np.append()

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [12]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [13]:
np.append(a,100)

array([ 95,  38,   7,  17,  56,  17,  27,  96,  64,  26,  49,  41,  89,
        10,  54, 100])

In [14]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

In [16]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[41., 61., 91., 21.,  1.],
       [82., 46., 62., 28.,  1.],
       [70., 72., 99., 60.,  1.],
       [79., 30., 68., 57.,  1.],
       [81., 74.,  8., 38.,  1.],
       [71., 11., 40., 63.,  1.]])

In [17]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[41.        , 61.        , 91.        , 21.        ,  0.83225206],
       [82.        , 46.        , 62.        , 28.        ,  0.26615457],
       [70.        , 72.        , 99.        , 60.        ,  0.83517895],
       [79.        , 30.        , 68.        , 57.        ,  0.59303229],
       [81.        , 74.        ,  8.        , 38.        ,  0.5814236 ],
       [71.        , 11.        , 40.        , 63.        ,  0.96184059]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [18]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [19]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [23]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [24]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [25]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [26]:
np.shape(a)

(15,)

In [27]:
np.expand_dims(a,axis=0)

array([[95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54]])

In [28]:
np.shape(np.expand_dims(a,axis=0))

(1, 15)

In [29]:
np.expand_dims(a,axis=1)

array([[95],
       [38],
       [ 7],
       [17],
       [56],
       [17],
       [27],
       [96],
       [64],
       [26],
       [49],
       [41],
       [89],
       [10],
       [54]])

In [30]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where


The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [31]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [32]:
# Q. Find all indices with value greater than 50

np.where(a>50)

(array([ 0,  4,  7,  8, 12, 14], dtype=int64),)

In [33]:
# Q. Replace all values > 50 with 0

#np.where(condition,true,false)

np.where(a>50,0,a)

array([ 0, 38,  7, 17,  0, 17, 27,  0,  0, 26, 49, 41,  0, 10,  0])

In [34]:
np.where(a%2==0,0,a)

array([95,  0,  7, 17,  0, 17, 27,  0,  0,  0, 49, 41, 89,  0,  0])

# np.argmax


The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [35]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [36]:
np.argmax(a)

7

In [37]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

In [38]:
np.argmax(b,axis=0)

array([1, 4, 2, 5], dtype=int64)

In [39]:
np.argmax(b,axis=1)

array([2, 0, 2, 0, 0, 0], dtype=int64)

# np.argmin

In [40]:
# this is the oposite of argmax

In [41]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [42]:
np.argmin(a)

2

In [43]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

In [44]:
np.argmin(b,axis=0)

array([0, 5, 4, 0], dtype=int64)

In [45]:
np.argmin(b,axis=1)

array([3, 3, 3, 1, 2, 1], dtype=int64)

# np.cumsum


numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [46]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [47]:
np.cumsum(a)

array([ 95, 133, 140, 157, 213, 230, 257, 353, 417, 443, 492, 533, 622,
       632, 686])

In [48]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

In [49]:
np.cumsum(b,axis=0)

array([[ 41,  61,  91,  21],
       [123, 107, 153,  49],
       [193, 179, 252, 109],
       [272, 209, 320, 166],
       [353, 283, 328, 204],
       [424, 294, 368, 267]])

In [50]:
np.cumsum(b,axis=1)

array([[ 41, 102, 193, 214],
       [ 82, 128, 190, 218],
       [ 70, 142, 241, 301],
       [ 79, 109, 177, 234],
       [ 81, 155, 163, 201],
       [ 71,  82, 122, 185]])

# np.cumprod

In [51]:
# It is also working like the cumsum if we do product replace of sum

In [52]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [53]:
np.cumprod(a)

array([         95,        3610,       25270,      429590,    24057040,
         408969680, -1842720528,  -807511552,  -141131776,   625541120,
         586743808, -1713307648,  2134441984,  -130416640,  1547436032])

In [54]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

In [55]:
np.cumprod(b,axis=0)

array([[        41,         61,         91,         21],
       [      3362,       2806,       5642,        588],
       [    235340,     202032,     558558,      35280],
       [  18591860,    6060960,   37981944,    2010960],
       [1505940660,  448511040,  303855552,   76416480],
       [-452395540,  638654144, -730679808,  519270944]])

In [56]:
np.cumprod(b,axis=1)

array([[      41,     2501,   227591,  4779411],
       [      82,     3772,   233864,  6548192],
       [      70,     5040,   498960, 29937600],
       [      79,     2370,   161160,  9186120],
       [      81,     5994,    47952,  1822176],
       [      71,      781,    31240,  1968120]])

# np.percentile


numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [57]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [58]:
np.percentile(a,50)

41.0

In [59]:
np.percentile(a,75)

60.0

In [60]:
np.percentile(a,25)

21.5

# np.histogram


Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [61]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [62]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 3, 2, 1, 2, 2, 1, 0, 1, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [63]:
np.histogram(a,bins=[0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

# np.corrcoef


Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [64]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [65]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin


With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [66]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [67]:
items=[10,20,30,40,50,60,70,80,90,100]

In [68]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False])

In [69]:
a[np.isin(a,items)]

array([10])

# np.flip


The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [70]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [71]:
np.flip(a)

array([54, 10, 89, 41, 49, 26, 64, 96, 27, 17, 56, 17,  7, 38, 95])

In [72]:
b

array([[41, 61, 91, 21],
       [82, 46, 62, 28],
       [70, 72, 99, 60],
       [79, 30, 68, 57],
       [81, 74,  8, 38],
       [71, 11, 40, 63]])

In [74]:
np.flip(b)

array([[63, 40, 11, 71],
       [38,  8, 74, 81],
       [57, 68, 30, 79],
       [60, 99, 72, 70],
       [28, 62, 46, 82],
       [21, 91, 61, 41]])

In [75]:
np.flip(b,axis=0)

array([[71, 11, 40, 63],
       [81, 74,  8, 38],
       [79, 30, 68, 57],
       [70, 72, 99, 60],
       [82, 46, 62, 28],
       [41, 61, 91, 21]])

In [76]:
np.flip(b,axis=1)

array([[21, 91, 61, 41],
       [28, 62, 46, 82],
       [60, 99, 72, 70],
       [57, 68, 30, 79],
       [38,  8, 74, 81],
       [63, 40, 11, 71]])

# np.put


The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [77]:
a

array([95, 38,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [78]:
np.put(a,[0,1],[96,39])

In [79]:
a

array([96, 39,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [80]:
# in this function the changes are permanently 
#np.put(array,index,values)

# np.delete


The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [81]:
a

array([96, 39,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [82]:
np.delete(a,0)

array([39,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [83]:
np.delete(a,[0,1,2])

array([17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [84]:
# np.delete(array,index)

# SET FUNCTIONS

### 1.np.union1d

In [85]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [86]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

### 2.np.intersect1d

In [87]:
np.intersect1d(m,n)

array([3, 4, 5])

### 3.np.setdiff1d

In [88]:
np.setdiff1d(m,n)  # elements of m which  are not in n

array([1, 2])

In [89]:
np.setdiff1d(n,m)  # elements of n which  are not in m

array([6, 7])

### 4.np.setxor1d

In [90]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [91]:
# remove the common element

### 5.np.in1d

In [93]:
np.in1d(m,3)

array([False, False,  True, False, False])

In [94]:
np.in1d(n,4)

array([False,  True, False, False, False])

In [95]:
# check the given element is in array or not
#np.in1d(array,element)

# np.clip


numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [96]:
a

array([96, 39,  7, 17, 56, 17, 27, 96, 64, 26, 49, 41, 89, 10, 54])

In [97]:
#np.clip(array,array_min=min range,array_max=max range)

np.clip(a,a_min=25,a_max=75)

array([75, 39, 25, 25, 56, 25, 27, 75, 64, 26, 49, 41, 75, 25, 54])