# Creating Numpy Array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
type(a)

numpy.ndarray

# 2D and 3D Array

In [9]:
b=np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Dtype

In [13]:
d=np.array([1,2,3],dtype=int)

In [14]:
d

array([1, 2, 3])

In [15]:
e=np.array([1,2,3],dtype=float)

In [16]:
e

array([1., 2., 3.])

In [19]:
f=np.array([-1,0,1],dtype=bool)

In [20]:
f

array([ True, False,  True])

In [21]:
g=np.array([1,2,3],dtype=complex)

In [22]:
g

array([1.+0.j, 2.+0.j, 3.+0.j])

# np.arange

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

# wirh reshape

In [25]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# np.ones and np.zeros

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.random

In [33]:
np.random.random((3,4))

array([[0.55821381, 0.65263519, 0.64463125, 0.48903858],
       [0.80791696, 0.06742922, 0.62455095, 0.91822892],
       [0.79982165, 0.29698444, 0.97571748, 0.27480905]])

In [34]:
np.random.random((4,6))

array([[0.67107235, 0.47223793, 0.25571682, 0.42492896, 0.92960132,
        0.12764816],
       [0.25470085, 0.74456718, 0.72713112, 0.53126936, 0.08118171,
        0.24317504],
       [0.05540217, 0.19699378, 0.99405643, 0.32006084, 0.39970374,
        0.76199247],
       [0.11716598, 0.93231081, 0.48114851, 0.54070749, 0.41386862,
        0.22983809]])

In [35]:
np.random.random((3,3))

array([[0.55512809, 0.90860349, 0.00801184],
       [0.9840721 , 0.2235002 , 0.54513879],
       [0.27103544, 0.16917639, 0.19096921]])

# np.linspace

In [36]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [37]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# np.identity

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Array Attributes

In [44]:
a1=np.arange(10)

In [45]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a2=np.arange(12,dtype=float).reshape(3,4)

In [48]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [49]:
a3=np.arange(8).reshape(2,2,2)

In [50]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# 1.ndim

In [52]:
a1.ndim

1

In [53]:
a2.ndim

2

In [54]:
a3.ndim

3

# 2.shape

In [55]:
a1.shape

(10,)

In [56]:
a2.shape

(3, 4)

In [57]:
a3.shape

(2, 2, 2)

# 3.size

In [58]:
a1.size

10

In [59]:
a2.size

12

In [60]:
a3.size

8

# 4.itemsize

In [61]:
a1.itemsize

4

In [62]:
a2.itemsize

8

In [63]:
a3.itemsize

4

# 5.dtype

In [64]:
a1.dtype

dtype('int32')

In [65]:
a2.dtype

dtype('float64')

In [66]:
a3.dtype

dtype('int32')

# Changing Datatype

# 1.astype()

In [67]:
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a1.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
a3.astype(np.float64)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [70]:
#generally we use this function to save the memory like float64 change in int32

# Array Operations

In [71]:
b1=np.arange(12).reshape(3,4)

In [72]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b2=np.arange(12,24).reshape(3,4)

In [74]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# (A) Scalar Operations

# 1.Airthmetic Operation

In [75]:
b1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [76]:
b1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [77]:
b1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [78]:
b1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [79]:
b1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# 2.Relational Operator

In [84]:
b2>19

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [85]:
b2>9

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
b2>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [87]:
b2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
b2<18

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

# (B).Vector Operations

# 1.Airthmetic Operation

In [89]:
b1 + b2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [90]:
b1 - b2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [91]:
b1 * b2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [94]:
c1=np.random.random((3,3))

In [96]:
c1=np.round(c1*100)

In [97]:
c1

array([[46., 13., 36.],
       [30., 32., 74.],
       [61., 61., 21.]])

# 1. max/min/sum/prod

In [98]:
np.max(c1)

74.0

In [99]:
np.min(c1)

13.0

In [100]:
np.sum(c1)

374.0

In [101]:
np.prod(c1)

119504869585920.0

In [102]:
np.max(c1,axis=0)

array([61., 61., 74.])

In [103]:
np.max(c1,axis=1)

array([46., 74., 61.])

In [104]:
#axis=0-->column and axis=1-->row

# 2.mean/median/std/var

In [105]:
np.mean(c1)

41.55555555555556

In [106]:
np.median(c1)

36.0

In [107]:
np.std(c1)

19.21290718421176

In [108]:
np.var(c1)

369.13580246913585

In [109]:
np.median(c1,axis=0)

array([46., 32., 36.])

In [110]:
np.median(c1,axis=1)

array([36., 32., 61.])

# 3.Dot product

In [111]:
d1=np.arange(12).reshape(3,4)

In [112]:
d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
d2=np.arange(12,24).reshape(4,3)

In [114]:
d2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [115]:
np.dot(d1,d2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [116]:
np.dot(d2,d1)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [117]:
#for dot product # column of d1 =# row of d2

# 4.log and exponents

In [119]:
np.log(d2)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [121]:
np.exp(d1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# 5.round/floor/ceil

In [154]:
e1=np.random.random((3,3))

In [155]:
e1

array([[0.93645873, 0.65456457, 0.2716915 ],
       [0.79674606, 0.36584489, 0.76118343],
       [0.42479372, 0.62053156, 0.21064608]])

In [151]:
np.random.random((2,3))

array([[0.88149006, 0.35909272, 0.12593008],
       [0.3958664 , 0.27082039, 0.63529801]])

In [152]:
np.round(np.random.random((2,3))*100)

array([[12., 68., 54.],
       [76., 81.,  6.]])

In [136]:
np.floor(np.random.random((2,3))*100)

array([[ 7., 62., 65.],
       [ 8., 36., 22.]])

In [137]:
np.ceil(np.random.random((2,3))*100)

array([[27., 18., 28.],
       [92., 25., 46.]])

In [156]:
e1=np.round(e1*100)

In [160]:
e1

array([[94., 65., 27.],
       [80., 37., 76.],
       [42., 62., 21.]])

In [161]:
#round-->convert into nearest integer
#floor-->convert 6.2 in 6 ,6.9 in 6
#ceil--> convert 6.2 in 7,7.9 in 8

In [162]:
l=np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])

In [163]:
np.round(l)

array([[ 1.,  2.,  3.],
       [ 4.,  6.,  7.],
       [ 8.,  9., 10.]])

In [164]:
np.floor(l)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [165]:
np.ceil(l)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

# Indexing and slicing

In [166]:
f1=np.arange(10)

In [167]:
f1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
f2=np.arange(12).reshape(3,4)

In [169]:
f2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
f3=np.arange(8).reshape(2,2,2)

In [171]:
f3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [172]:
f1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
f1[-1]

9

In [174]:
f1[0]

0

In [175]:
f2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
f2[1,2]

6

In [177]:
f2[2,3]

11

In [185]:
f2[1,0]
#f2[rpw,column]

4

In [179]:
f3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [180]:
f3[1,0,1]

5

In [181]:
f3[0,1,0]

2

In [182]:
f3[0,0,0]

0

In [183]:
#f3[array number,row,column]

In [186]:
f3[1,1,0]

6

In [187]:
#Slicing

In [188]:
f1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
f1[2:5]

array([2, 3, 4])

In [190]:
f2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
f2[0,:]

array([0, 1, 2, 3])

In [193]:
f2[:,2]

array([ 2,  6, 10])

In [195]:
f2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [196]:
f2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [198]:
f2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [199]:
f2[1,0::3]

array([4, 7])

In [207]:
f2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [209]:
f4=np.arange(27).reshape(3,3,3)

In [210]:
f4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [211]:
f4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [212]:
f4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [213]:
f4[0,1]

array([3, 4, 5])

In [214]:
f4[1,:,1]

array([10, 13, 16])

In [215]:
f4[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [220]:
f4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [221]:
f1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
for i in f1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [229]:
f2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [230]:
for i in f2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [233]:
f4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [234]:
for i in f4:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [235]:
for i in np.nditer(f4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [236]:
for i in np.nditer(f2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


# **Reshaping**

# 1.Reshape

In [237]:
f1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
f1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [239]:
f1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# 2.Transpose

In [240]:
f1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [246]:
f1=f1.reshape(1,10)

In [247]:
f1.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [244]:
f2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [245]:
f2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# 3.ravel

In [249]:
f1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [250]:
f2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [251]:
f3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [252]:
f4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

# 1.Horizontal stacking

In [253]:
g1=np.arange(12).reshape(3,4)

In [254]:
g1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [255]:
g2=np.arange(12,24).reshape(3,4)

In [256]:
g2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [264]:
h1=np.hstack((g1,g2))

In [265]:
h1

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [266]:
h2=np.hstack((g1,g2,g1,g2))

In [267]:
h2

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

# 2.Vertical Stacking

In [268]:
h3=np.vstack((g1,g2))

In [269]:
h3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [270]:
h4=np.vstack((g1,g2,g1,g2))

In [271]:
h4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

# 1.Horizontal Spliting

In [274]:
np.hsplit(h1,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [275]:
np.hsplit(h2,4)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [276]:
np.hsplit(h1,4)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

# 2.Vertical spliting

In [277]:
np.vsplit(h3,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [279]:
np.vsplit(h4,4)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]